version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies with verbose logging"
      - npm install --loglevel verbose --legacy-peer-deps --unsafe-perm

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"